### ISSUE TITLE
Python path twiddling

### ISSUE THREAD

**Issue by nickjalbert** [nickjalbert/improved-funicular#21]
I've been twiddling with the Python paths and think I've landed on a reasonable solution.

**Problem:** I wanted to be able to import envs/strategies in subdirectories without a bunch of dumb path manipulation etc, for example [this import here](https://github.com/nickjalbert/improved-funicular/blob/42973cda2af8453a3b799085597aca2c17a2ab93/tests/perf_benchmarks.py#L9).

**Solution:** Add a [.pth file to the site-packages directory in the virtualenv](https://stackoverflow.com/a/10739838).

For me, this entailed running 
``` 
echo `pwd`/ > improved-funicular/lib/python3.7/site-packages/curr_dir.pth 
``` 

from the root directory of `improved-funicular`.  Now the root dir is automatically added to the search path whenever I activate the virtualenv so, for example, `python tests/perf_benchmarks.py` just works now.

Anyway, wanted to highlight this for you in case you want to do the same.

**Comment by nickjalbert** [comment]
Seems like this already worked in some cases (e.g. importing envs in strategies).  Obvi I'm not an expert on this; let me know if you know a better way!

**Comment by andyk** [comment]
Thanks for the heads up!

> Seems like this already worked in some cases (e.g. importing envs in strategies). Obvi I'm not an expert on this; let me know if you know a better way!

Hmm, I'm guessing it only works as long as the PYTHONPATH makes sense given the working directory things got run from. I use PyCharm most of the time and use the project root as my working directory and PyCharm figured it out somehow I guess because the module, i.e. dot, notation in import statements aligns with the path structure python finds from that working dir.

I did notice when I was doing experiments on EC2 that I had to use `PYTHONPATH=./ python contrib/ray_algo.py` to get things to work...

I'm def not an expert on this stuff either, so the solution you proposed seems good to me! Though I actually use miniconda, not virtualenv, but same idea
